[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "frozen enroll protect secret deputy miracle slender film one sketch ignore trash bamboo multiply slot nation congress slight pattern body sudden prize still crazy"
